function xhr(c,a){var b=new XMLHttpRequest;b.open(c,a);b.setRequestHeader("X-Requested-With","CNTP");b.onerror=function(){console.log('[XHR ERROR] Failed to "'+c+'" '+a+": "+b.status)};return b}
function show_tab(c){document.getElementById("msg").innerHTML="";var a=document.getElementsByClassName("tab");for(i=0;i<a.length;i++)a[i].style.display=a[i].id=="tab_"+c?"block":"none";a=document.getElementsByClassName("link");for(i=0;i<a.length;i++)a[i].className=a[i].id==c?a[i].className+" active":"link"}
function parse_url(c){var a=document.getElementById("msg");c=c.split("?");for(var b=0;b<c.length;b++){var e=c[b].split("=");"tab"==e[0]?show_tab(e[1]):"b_cat"==e[0]?(document.getElementById("b_cats").value=e[1],cat_load()):"saved"==e[0]?a.innerHTML="<b id='ok'>[SUCCESS]</b> Configuration updated!":"feed_updated"==e[0]?a.innerHTML="<b id='ok'>[SUCCESS]</b> Feed updated!":"feed_created"==e[0]?a.innerHTML="<b id='ok'>[SUCCESS]</b> Feed created!":"feed_removed"==e[0]?a.innerHTML="<b id='ok'>[SUCCESS]</b> Feed removed!":
"feed_locked"==e[0]?a.innerHTML="<b id='warn'>[ERROR]</b> Feed is in use!":"b_cat_added"==e[0]?a.innerHTML="<b id='ok'>[SUCCESS]</b> New Bookmark Category added!":"b_cat_saved"==e[0]?a.innerHTML="<b id='ok'>[SUCCESS]</b> Bookmark Category saved!":"b_cat_removed"==e[0]?a.innerHTML="<b id='ok'>[SUCCESS]</b> Bookmark Category removed!":"b_removed"==e[0]?a.innerHTML="<b id='ok'>[SUCCESS]</b> Bookmark deleted!":"failed"==e[0]?a.innerHTML="<b id='warn'>[ERROR]</b> Configuration could not be saved!":"demo"==
e[0]?a.innerHTML="<b id='warn'>[ERROR]</b> Configuration cannot be changed during the demo!":"empty"==e[0]?a.innerHTML="<b id='warn'>[ERROR]</b> Please fill out all fields!":"css_url"==e[0]?a.innerHTML="<b id='warn'>[ERROR]</b> External CSS file not found!":"invalid"==e[0]?a.innerHTML="<b id='warn'>[ERROR]</b> New Email Address seems to be invalid, please check!":"match"==e[0]?a.innerHTML="<b id='warn'>[ERROR]</b> Passwords do not match! tYp0?":"pwd"==e[0]?a.innerHTML="<b id='warn'>[ERROR]</b> Wrong Password!":
"pwdmail"==e[0]&&(a.innerHTML="<b id='warn'>[ERROR]</b> Wrong Password or email address!")}}
function feed_edit(){var c=document.getElementById("feed_edit_select").value;if("none"!==c){var a=xhr("GET","php/settings_worker.php?feed_edit="+c);a.onload=function(){if(200<=a.status&&400>a.status){var b=JSON.parse(a.response);document.getElementById("feed_name").value=b[0];document.getElementById("feed_desc").value=b[1];document.getElementById("feed_url").value=b[2];document.getElementById("feed_website").value=b[3];document.getElementById("feed_thumb").checked=b[4]?!0:!1}};a.send()}}
function cat_add(){var c=document.getElementById("cat_name_new").value;if(c){var a=xhr("POST","php/settings_worker.php");a.setRequestHeader("Content-Type","application/x-www-form-urlencoded; charset=UTF-8");a.onreadystatechange=function(){4==a.readyState&&200==a.status&&window.location.replace("/settings.php?tab=bookmarks?b_cat_added")};a.send("b_cat_add="+encodeURIComponent(c))}else window.location.replace("/settings.php?tab=bookmarks?empty")}
function cat_load(){var c=document.getElementById("b_cats").value;if("none"!==c){var a=xhr("GET","php/settings_worker.php?b_cat_load="+c);a.onload=function(){if(200<=a.status&&400>a.status){var b=JSON.parse(a.response),e=b[0];b=b[1];var d=document.getElementById("b_box");var n='<br><input type="radio" id="cat_left" name="position" value="0" checked="checked">Left</input><input type="radio" id="cat_right" name="position" value="1">Right</input><br><button class="btn_cat_del"><img src="css/_main/delete.svg" alt="delete" height="22" width="22">Remove Category</button><button class="btn_b_add"><img src="css/_main/add.svg" alt="create" height="22" width="22">Add Bookmark</button><button class="btn_cat_save"><img src="css/_main/save.svg" alt="create" height="22" width="22">Save Category</button><br><div id="b_box_cont">';
if(0!==b.length){for(var f=0;f<b.length;f++)n+='<div class="b_entry" id="'+b[f][0]+'"><div class="b_name"><img src="css/_main/title.svg" alt="name" height="22" width="22"><input class="inp_b_name" type="text" placeholder="Name..." value="'+b[f][1]+'"></div><div class="b_url"><img src="css/_main/url.svg" alt="url" height="22" width="22"><input class="inp_b_url" type="text" placeholder="URL..." value="'+b[f][2]+'"><button class="btn_b_del" id="'+b[f][0]+'"><img src="css/_main/remove.svg" alt="create" height="22" width="22"></button></div></div>';
n+='</div><br><button class="btn_cat_del"><img src="css/_main/delete.svg" alt="delete" height="22" width="22">Remove Category</button><button class="btn_b_add"><img src="css/_main/add.svg" alt="create" height="22" width="22">Add Bookmark</button><button class="btn_cat_save"><img src="css/_main/save.svg" alt="create" height="22" width="22">Save Category</button>'}d.innerHTML=n;e&&(document.getElementById("cat_right").checked=!0);document.querySelectorAll(".btn_b_del").forEach(function(p){p.addEventListener("click",
function(){bookmark_del(p.id,c)},!1)});document.querySelectorAll(".btn_cat_del").forEach(function(p){p.addEventListener("click",function(){cat_del(c)},!1)});document.querySelectorAll(".btn_b_add").forEach(function(p){p.addEventListener("click",bookmark_add,!1)});document.querySelectorAll(".btn_cat_save").forEach(function(p){p.addEventListener("click",function(){cat_save(c)},!1)})}};a.send()}else document.getElementById("b_box").innerHTML=""}
function cat_del(c){var a=xhr("POST","php/settings_worker.php");a.setRequestHeader("Content-Type","application/x-www-form-urlencoded; charset=UTF-8");a.onreadystatechange=function(){4==a.readyState&&200==a.status&&window.location.replace("/settings.php?tab=bookmarks?b_cat_removed")};a.send("b_cat_del="+c)}
function cat_save(c){var a=xhr("POST","php/settings_worker.php");a.setRequestHeader("Content-Type","application/x-www-form-urlencoded; charset=UTF-8");var b=0;document.getElementById("cat_right").checked&&(b=1);a.send("cat_id="+c+"&cat_pos="+b);a=document.querySelectorAll(".b_entry");var e=a.length;a.forEach(function(d){var n=d.id,f=d.children[0].children[1].value;d=d.children[1].children[1].value;if(f&&d){var p=xhr("POST","php/settings_worker.php");p.setRequestHeader("Content-Type","application/x-www-form-urlencoded; charset=UTF-8");
p.onreadystatechange=function(){if(4==p.readyState&&200==p.status&&(e--,0===e)){var h=xhr("POST","php/settings_worker.php");h.setRequestHeader("Content-Type","application/x-www-form-urlencoded; charset=UTF-8");h.onreadystatechange=function(){4==h.readyState&&200==h.status&&window.location.replace("/settings.php?tab=bookmarks?b_cat="+c+"?b_cat_saved")};h.send("b_cache")}};n?p.send("cat_id="+c+"&b_id="+n+"&b_name="+encodeURIComponent(f)+"&b_url="+encodeURIComponent(d)):p.send("cat_id="+c+"&b_id=new&b_name="+
encodeURIComponent(f)+"&b_url="+encodeURIComponent(d))}else document.getElementById("msg").innerHTML="<b id='warn'>[ERROR]</b> Please fill out all fields!"})}
function bookmark_add(){document.getElementById("b_box_cont").innerHTML+='<div class="b_entry new"><div class="b_name"><img src="css/_main/title.svg" alt="name" height="22" width="22"><input class="inp_b_name" type="text" placeholder="Name..."></div><div class="b_url"><img src="css/_main/url.svg" alt="url" height="22" width="22"><input class="inp_b_url" type="text" placeholder="URL..."><button class="btn_b_del btn_new"><img src="css/_main/remove.svg" alt="create" height="22" width="22"></button></div></div><br>';document.querySelectorAll(".btn_new").forEach(function(c){c.addEventListener("click",
function(){c.parentNode.parentNode.parentNode.removeChild(this.parentNode.parentNode)},!1)})}function bookmark_del(c,a){var b=xhr("POST","php/settings_worker.php");b.setRequestHeader("Content-Type","application/x-www-form-urlencoded; charset=UTF-8");b.onreadystatechange=function(){4==b.readyState&&200==b.status&&window.location.replace("/settings.php?tab=bookmarks?b_cat="+a+"?b_removed")};b.send("b_del="+c+"&cat_id="+a)}
function weather_update(){var c=xhr("POST","php/settings_worker.php");c.setRequestHeader("Content-Type","application/x-www-form-urlencoded; charset=UTF-8");c.onreadystatechange=function(){4==c.readyState&&200==c.status&&(document.getElementById("msg").innerHTML="<b id='ok'>[SUCCESS]</b> Weather cache cleared!")};c.send("w_update")}
function weather_icon(){var c=document.getElementById("weather_icon").value,a=xhr("GET","php/settings_worker.php?w_icon="+c);a.onload=function(){if(200<=a.status&&400>a.status){var b=JSON.parse(a.response);b='<a href="'+b[2]+'"><img src="weather/'+b[0]+"/01d."+b[1]+'"><img src="weather/'+b[0]+"/02n."+b[1]+'"><img src="weather/'+b[0]+"/25d."+b[1]+'"><br>'+b[0]+"</a>";document.getElementById("weather_icon_prev").innerHTML=b}};a.send()}
function layout_creater_options(){for(var c=Number(document.getElementById("layout_row").value),a=Number(document.getElementById("layout_column").value),b="",e=1,d=0;d<c;d++){for(var n=0;n<a;n++)b+='<select id="ls_'+e+'" class="layout_select" value="feed">',b+='<option value="feed" selected="selected">Feed</option>               <option value="bookmarks">Bookmarks</option>               <option value="notes">Notes</option>               <option value="weather">Weather</option>',0<d&&(b+='<option value="rowspan">\u2193 Rowspan</option>'),
0<n&&(b+='<option value="colspan">\u2192 Colspan</option>'),b+="</select>",e++;b+="<br>"}document.getElementById("layout_create").innerHTML=b;document.querySelectorAll(".layout_select").forEach(function(f){f.addEventListener("click",layout_creater_update,!1)})}
function layout_creater_init(){var c=document.getElementById("layout_preview").rows,a=c.length;document.getElementById("layout_row").value=a;for(var b=c[0].cells,e=b.length,d=0;d<b.length;d++)1<b[d].colSpan&&(e+=b[d].colSpan-1);document.getElementById("layout_column").value=e;layout_creater_options();b=Array(a).fill(0).map(function(w){return Array(e).fill(0)});for(d=0;d<a;d++)for(var n=c[d].cells,f=0,p=0,h=n.length;p<h;p++){for(var g=n[p];b[d][f];)f++;var k=0;if(1<g.colSpan){var l=f+g.colSpan;k=1}else l=
f+1;var m=0;if(1<g.rowSpan){var q=d+g.rowSpan;m=1}else q=d+1;for(var r=d,t=1;r<q;r++)for(var u=f,v=1;u<l;u++)k&&0===v?b[r][u]="colspan":m&&0===t?b[r][u]="rowspan":(k&&1===v&&(v=0),m&&1===t&&(t=0),b[r][u]=g.id?g.id:"feed");f=l}c=1;for(d=0;d<a;d++)for(n=0;n<e;n++)f=document.getElementById("ls_"+c),"rowspan"===b[d][n]?f.value="rowspan":"colspan"===b[d][n]?f.value="colspan":"feed"===b[d][n]?(f.value="feed",feed_count++):"bookmarks"===b[d][n]?f.value="bookmarks":"notes"===b[d][n]?f.value="notes":"weather"===
b[d][n]&&(f.value="weather"),c++;layout_creater_update()}
function layout_creater_update(){for(var c={},a=0;2>a;c={$jscomp$loop$prop$column_count$26:c.$jscomp$loop$prop$column_count$26},a++){var b=Number(document.getElementById("layout_row").value);c.$jscomp$loop$prop$column_count$26=Number(document.getElementById("layout_column").value);for(var e=Array(b).fill(0).map(function(t){return function(u){return Array(t.$jscomp$loop$prop$column_count$26).fill(0)}}(c)),d=Array(b).fill(0).map(function(t){return function(u){return Array(t.$jscomp$loop$prop$column_count$26).fill(0)}}(c)),n=
0,f=0,p=0,h=1,g=0;g<b;g++)for(var k=0,l="";k<c.$jscomp$loop$prop$column_count$26;k++){var m=document.getElementById("ls_"+h);m.disabled=!1;var q=m.value;"bookmarks"===q?n=h:"notes"===q?p=h:"weather"===q?f=h:"rowspan"===q?e[g][k]=1:"colspan"===q&&(d[g][k]=1);l='<option value="feed">Feed</option>';l+='<option value="bookmarks">Bookmarks</option>';l+='<option value="notes">Notes</option>';l+='<option value="weather">Weather</option>';0<g&&(l+='<option value="rowspan">\u2193 Rowspan</option>');0<k&&(l+=
'<option value="colspan">\u2192 Colspan</option>');m.innerHTML=l;m.value=q;h++}h=1;for(g=0;g<b;g++)for(k=0;k<c.$jscomp$loop$prop$column_count$26;k++){l=document.getElementById("ls_"+h).value;if("rowspan"===l&&(d[g-1][k]||d[g-1][k+1])){for(m=1;k+m<c.$jscomp$loop$prop$column_count$26&&d[g-1][k+m];)document.getElementById("ls_"+(h+m)).value="rowspan",m++;for(m=1;0<=k-m&&d[g-1][k-m+1];)document.getElementById("ls_"+(h-m)).value="rowspan",m++}if("rowspan"===l&&1<g&&e[g-1][k])for(m=1;0<=g-m;){if(d[g-m][k]||
d[g-m][k+1]){for(var r=0;d[g-m][k-r];)r++;for(q=0;d[g-m][k+q];)q++;for(r=-r;r<q;r++)document.getElementById("ls_"+(h+r)).value="rowspan"}if("rowspan"!==document.getElementById("ls_"+(h-c.$jscomp$loop$prop$column_count$26*m)).value)break;m++}if("colspan"===l&&(e[g][k-1]||g+1<b&&e[g+1][k-1])){for(l=0;0<g-l&&e[g-l][k-1];)document.getElementById("ls_"+(h-c.$jscomp$loop$prop$column_count$26*l)).value="rowspan",l++;document.getElementById("ls_"+(h-c.$jscomp$loop$prop$column_count$26*l)).value="colspan";
for(l=1;g+l<b&&e[g+l][k-1];)document.getElementById("ls_"+(h+c.$jscomp$loop$prop$column_count$26*l)).value="rowspan",l++}h++}h=1;for(g=0;g<b;g++)for(k=0,l="";k<c.$jscomp$loop$prop$column_count$26;k++){m=document.getElementById("ls_"+h);q=m.value;l='<option value="feed">Feed</option>';n&&n!==h||(l+='<option value="bookmarks">Bookmarks</option>');p&&p!==h||(l+='<option value="notes">Notes</option>');f&&f!==h||(l+='<option value="weather">Weather</option>');if(0<g&&(l+='<option value="rowspan">\u2193 Rowspan</option>',
"rowspan"===q))for(g<b-1&&e[g+1][k]&&(m.disabled=!0),r=1;0<=g-r;){d[g-r][k]&&(m.disabled=!0,document.getElementById("ls_"+(h-1)).disabled=!0);if("rowspan"!==document.getElementById("ls_"+(h-c.$jscomp$loop$prop$column_count$26*r)).value)break;r++}0<k&&(l+='<option value="colspan">\u2192 Colspan</option>',"colspan"===q&&k<c.$jscomp$loop$prop$column_count$26-1&&d[g][k+1]&&(m.disabled=!0));m.innerHTML=l;m.value=q;h++}}layout_update_preview(1)}
function layout_update_preview(c){for(var a=Number(document.getElementById("layout_row").value),b=Number(document.getElementById("layout_column").value),e=!1,d=!1,n=!1,f,p=0,h="<tbody>",g=1,k=0;k<a;k++){h+="<tr>";for(var l=0;l<b;l++){f=document.getElementById("ls_"+g);if("rowspan"!==f.value&&"colspan"!==f.value){"bookmarks"===f.value&&!1===e?(h+='<td id="bookmarks"',e=!0,f="B"):"notes"===f.value&&!1===n?(h+='<td id="notes"',n=!0,f="N"):"weather"===f.value&&!1===d?(h+='<td id="weather"',d=!0,f="W"):
(h+='<td class="feed_box"',p++,f=p);for(var m=1,q=g+b;document.getElementById("ls_"+q)&&"rowspan"===document.getElementById("ls_"+q).value;)m++,q+=b;q=1;for(var r=g+1;document.getElementById("ls_"+r)&&"colspan"===document.getElementById("ls_"+r).value;)q++,r++;1<m&&(h+=' rowspan="'+m+'"');1<q&&(h+=' colspan="'+q+'"');h+=">";c&&(h+=f);h+="</td>"}g++}h+="</tr>"}h+="</tbody>";document.getElementById("layout_preview").innerHTML=h;document.getElementById("feed_count").innerHTML=p}
function layout_save(){layout_update_preview(0);var c=document.getElementById("feed_count").innerHTML,a=document.getElementById("layout_preview"),b=a.children[0].innerHTML,e=0,d=0,n=0;null!=a.querySelector("#bookmarks")&&(e=1);null!=a.querySelector("#notes")&&(d=1);null!=a.querySelector("#weather")&&(n=1);console.log("b:"+e+" n:"+d+" w:"+n);var f=xhr("POST","php/settings_worker.php");f.setRequestHeader("Content-Type","application/x-www-form-urlencoded; charset=UTF-8");f.onreadystatechange=function(){4==
f.readyState&&200==f.status&&window.location.replace("/settings.php?tab=layout?saved")};f.send("feed_count="+c+"&table="+encodeURIComponent(b)+"&b="+e+"&n="+d+"&w="+n)}function theme_preview(){var c=document.getElementById("theme_select").value;document.getElementById("theme_prev").innerHTML='<img src="css/_prev/'+c+'.png" alt="preview">'}
document.addEventListener("DOMContentLoaded",function(){show_tab("feeds");document.getElementById("layout").addEventListener("click",function(){show_tab("layout")},!1);document.getElementById("theme").addEventListener("click",function(){show_tab("theme")},!1);document.getElementById("user").addEventListener("click",function(){show_tab("user")},!1);document.getElementById("feeds").addEventListener("click",function(){show_tab("feeds")},!1);document.getElementById("bookmarks").addEventListener("click",
function(){show_tab("bookmarks")},!1);document.getElementById("weather").addEventListener("click",function(){show_tab("weather")},!1);parse_url(location.search.substr(1));document.getElementById("feed_edit_select").addEventListener("click",function(){feed_edit()},!1);document.getElementById("btn_cat_add").addEventListener("click",function(){cat_add()},!1);document.getElementById("b_cats").addEventListener("click",function(){cat_load()},!1);document.getElementById("weather_update").addEventListener("click",
function(){weather_update()},!1);document.getElementById("weather_icon").addEventListener("click",function(){weather_icon()},!1);weather_icon();layout_creater_init();document.getElementById("layout_row").addEventListener("click",function(){layout_creater_options();layout_creater_update()},!1);document.getElementById("layout_column").addEventListener("click",function(){layout_creater_options();layout_creater_update()},!1);document.getElementById("theme_select").addEventListener("click",function(){theme_preview()},
!1);theme_preview();document.getElementById("layout_save").addEventListener("click",function(){layout_save()},!1)});