function xhr(c,b){var a=new XMLHttpRequest;a.open(c,b);a.setRequestHeader("X-Requested-With","CNTP");a.onerror=function(){console.log('[XHR ERROR] Failed to "'+c+'" '+b+": "+a.status)};return a}
function show_tab(c){document.getElementById("msg").innerHTML="";var b=document.getElementsByClassName("tab");for(i=0;i<b.length;i++)b[i].style.display=b[i].id=="tab_"+c?"block":"none";b=document.getElementsByClassName("link");for(i=0;i<b.length;i++)b[i].className=b[i].id==c?b[i].className+" active":"link"}
function parse_url(c){var b=document.getElementById("msg");c=c.split("?");for(var a=0;a<c.length;a++){var e=c[a].split("=");"tab"==e[0]?show_tab(e[1]):"b_cat"==e[0]?(document.getElementById("b_cats").value=e[1],cat_load()):"saved"==e[0]?b.innerHTML="<b id='ok'>[SUCCESS]</b> Configuration updated!":"feed_updated"==e[0]?b.innerHTML="<b id='ok'>[SUCCESS]</b> Feed updated!":"feed_created"==e[0]?b.innerHTML="<b id='ok'>[SUCCESS]</b> Feed created!":"feed_removed"==e[0]?b.innerHTML="<b id='ok'>[SUCCESS]</b> Feed removed!":
"feed_locked"==e[0]?b.innerHTML="<b id='warn'>[ERROR]</b> Feed is in use!":"b_cat_added"==e[0]?b.innerHTML="<b id='ok'>[SUCCESS]</b> New Bookmark Category added!":"b_cat_saved"==e[0]?b.innerHTML="<b id='ok'>[SUCCESS]</b> Bookmark Category saved!":"b_cat_removed"==e[0]?b.innerHTML="<b id='ok'>[SUCCESS]</b> Bookmark Category removed!":"b_removed"==e[0]?b.innerHTML="<b id='ok'>[SUCCESS]</b> Bookmark deleted!":"failed"==e[0]?b.innerHTML="<b id='warn'>[ERROR]</b> Configuration could not be saved!":"demo"==
e[0]?b.innerHTML="<b id='warn'>[ERROR]</b> Configuration cannot be changed during the demo!":"empty"==e[0]?b.innerHTML="<b id='warn'>[ERROR]</b> Please fill out all fields!":"css_url"==e[0]?b.innerHTML="<b id='warn'>[ERROR]</b> External CSS file not found!":"invalid"==e[0]?b.innerHTML="<b id='warn'>[ERROR]</b> New Email Address seems to be invalid, please check!":"match"==e[0]?b.innerHTML="<b id='warn'>[ERROR]</b> Passwords do not match! tYp0?":"pwd"==e[0]?b.innerHTML="<b id='warn'>[ERROR]</b> Wrong Password!":
"pwdmail"==e[0]&&(b.innerHTML="<b id='warn'>[ERROR]</b> Wrong Password or email address!")}}
function feed_edit(){var c=document.getElementById("feed_edit_select").value;if("none"!==c){var b=xhr("GET","php/settings_worker.php?feed_edit="+c);b.onload=function(){if(200<=b.status&&400>b.status){var a=JSON.parse(b.response);document.getElementById("feed_name").value=a[0];document.getElementById("feed_desc").value=a[1];document.getElementById("feed_url").value=a[2];document.getElementById("feed_website").value=a[3];document.getElementById("feed_thumb").checked=a[4]?!0:!1}};b.send()}}
function cat_add(){var c=document.getElementById("cat_name_new").value;if(c){var b=xhr("POST","php/settings_worker.php");b.setRequestHeader("Content-Type","application/x-www-form-urlencoded; charset=UTF-8");b.onreadystatechange=function(){4==b.readyState&&200==b.status&&window.location.replace("/settings.php?tab=bookmarks?b_cat_added")};b.send("b_cat_add="+encodeURIComponent(c))}else window.location.replace("/settings.php?tab=bookmarks?empty")}
function cat_load(){var c=document.getElementById("b_cats").value;if("none"!==c){var b=xhr("GET","php/settings_worker.php?b_cat_load="+c);b.onload=function(){if(200<=b.status&&400>b.status){var a=JSON.parse(b.response),e=a[0];a=a[1];var d=document.getElementById("b_box");var n='<br><input type="radio" id="cat_left" name="position" value="0" checked="checked">Left</input><input type="radio" id="cat_right" name="position" value="1">Right</input><br><button class="btn_cat_del"><img src="css/_main/delete.svg" alt="delete" height="22" width="22">Remove Category</button><button class="btn_b_add"><img src="css/_main/add.svg" alt="create" height="22" width="22">Add Bookmark</button><button class="btn_cat_save"><img src="css/_main/save.svg" alt="create" height="22" width="22">Save Category</button><br><div id="b_box_cont">';
if(0!==a.length){for(var g=0;g<a.length;g++)n+='<div class="b_entry" id="'+a[g][0]+'"><div class="b_name"><img src="css/_main/title.svg" alt="name" height="22" width="22"><input class="inp_b_name" type="text" placeholder="Name..." value="'+a[g][1]+'"></div><div class="b_url"><img src="css/_main/url.svg" alt="url" height="22" width="22"><input class="inp_b_url" type="text" placeholder="URL..." value="'+a[g][2]+'"><button class="btn_b_del" id="'+a[g][0]+'"><img src="css/_main/remove.svg" alt="create" height="22" width="22"></button></div></div>';
n+='</div><br><button class="btn_cat_del"><img src="css/_main/delete.svg" alt="delete" height="22" width="22">Remove Category</button><button class="btn_b_add"><img src="css/_main/add.svg" alt="create" height="22" width="22">Add Bookmark</button><button class="btn_cat_save"><img src="css/_main/save.svg" alt="create" height="22" width="22">Save Category</button>'}d.innerHTML=n;e&&(document.getElementById("cat_right").checked=!0);document.querySelectorAll(".btn_b_del").forEach(function(a){a.addEventListener("click",
function(){bookmark_del(a.id,c)},!1)});document.querySelectorAll(".btn_cat_del").forEach(function(a){a.addEventListener("click",function(){cat_del(c)},!1)});document.querySelectorAll(".btn_b_add").forEach(function(a){a.addEventListener("click",bookmark_add,!1)});document.querySelectorAll(".btn_cat_save").forEach(function(a){a.addEventListener("click",function(){cat_save(c)},!1)})}};b.send()}else document.getElementById("b_box").innerHTML=""}
function cat_del(c){var b=xhr("POST","php/settings_worker.php");b.setRequestHeader("Content-Type","application/x-www-form-urlencoded; charset=UTF-8");b.onreadystatechange=function(){4==b.readyState&&200==b.status&&window.location.replace("/settings.php?tab=bookmarks?b_cat_removed")};b.send("b_cat_del="+c)}
function cat_save(c){var b=xhr("POST","php/settings_worker.php");b.setRequestHeader("Content-Type","application/x-www-form-urlencoded; charset=UTF-8");var a=0;document.getElementById("cat_right").checked&&(a=1);b.send("cat_id="+c+"&cat_pos="+a);b=document.querySelectorAll(".b_entry");var e=b.length;b.forEach(function(a){var b=a.id,d=a.children[0].children[1].value;a=a.children[1].children[1].value;if(d&&a){var q=xhr("POST","php/settings_worker.php");q.setRequestHeader("Content-Type","application/x-www-form-urlencoded; charset=UTF-8");
q.onreadystatechange=function(){if(4==q.readyState&&200==q.status&&(e--,0===e)){var a=xhr("POST","php/settings_worker.php");a.setRequestHeader("Content-Type","application/x-www-form-urlencoded; charset=UTF-8");a.onreadystatechange=function(){4==a.readyState&&200==a.status&&window.location.replace("/settings.php?tab=bookmarks?b_cat="+c+"?b_cat_saved")};a.send("b_cache")}};b?q.send("cat_id="+c+"&b_id="+b+"&b_name="+encodeURIComponent(d)+"&b_url="+encodeURIComponent(a)):q.send("cat_id="+c+"&b_id=new&b_name="+
encodeURIComponent(d)+"&b_url="+encodeURIComponent(a))}else document.getElementById("msg").innerHTML="<b id='warn'>[ERROR]</b> Please fill out all fields!"})}
function bookmark_add(){document.getElementById("b_box_cont").innerHTML+='<div class="b_entry new"><div class="b_name"><img src="css/_main/title.svg" alt="name" height="22" width="22"><input class="inp_b_name" type="text" placeholder="Name..."></div><div class="b_url"><img src="css/_main/url.svg" alt="url" height="22" width="22"><input class="inp_b_url" type="text" placeholder="URL..."><button class="btn_b_del btn_new"><img src="css/_main/remove.svg" alt="create" height="22" width="22"></button></div></div><br>';document.querySelectorAll(".btn_new").forEach(function(c){c.addEventListener("click",
function(){c.parentNode.parentNode.parentNode.removeChild(this.parentNode.parentNode)},!1)})}function bookmark_del(c,b){var a=xhr("POST","php/settings_worker.php");a.setRequestHeader("Content-Type","application/x-www-form-urlencoded; charset=UTF-8");a.onreadystatechange=function(){4==a.readyState&&200==a.status&&window.location.replace("/settings.php?tab=bookmarks?b_cat="+b+"?b_removed")};a.send("b_del="+c+"&cat_id="+b)}
function weather_update(){var c=xhr("POST","php/settings_worker.php");c.setRequestHeader("Content-Type","application/x-www-form-urlencoded; charset=UTF-8");c.onreadystatechange=function(){4==c.readyState&&200==c.status&&(document.getElementById("msg").innerHTML="<b id='ok'>[SUCCESS]</b> Weather cache cleared!")};c.send("w_update")}
function weather_icon(){var c=document.getElementById("weather_icon").value,b=xhr("GET","php/settings_worker.php?w_icon="+c);b.onload=function(){if(200<=b.status&&400>b.status){var a=JSON.parse(b.response);a='<a href="'+a[2]+'"><img src="weather/'+a[0]+"/01d."+a[1]+'"><img src="weather/'+a[0]+"/02n."+a[1]+'"><img src="weather/'+a[0]+"/25d."+a[1]+'"><br>'+a[0]+"</a>";document.getElementById("weather_icon_prev").innerHTML=a}};b.send()}
function layout_creater_options(){for(var c=Number(document.getElementById("layout_row").value),b=Number(document.getElementById("layout_column").value),a="",e=1,d=0;d<c;d++){for(var n=0;n<b;n++)a+='<select id="ls_'+e+'" class="layout_select" value="feed">',a+='<option value="feed" selected="selected">Feed</option>               <option value="bookmarks">Bookmarks</option>               <option value="notes">Notes</option>               <option value="weather">Weather</option>',0<d&&(a+='<option value="rowspan">\u2193 Rowspan</option>'),
0<n&&(a+='<option value="colspan">\u2192 Colspan</option>'),a+="</select>",e++;a+="<br>"}document.getElementById("layout_create").innerHTML=a;document.querySelectorAll(".layout_select").forEach(function(a){a.addEventListener("click",layout_creater_update,!1)})}
function layout_creater_init(){var c=document.getElementById("layout_preview").rows,b=c.length;document.getElementById("layout_row").value=b;for(var a=c[0].cells,e=a.length,d=0;d<a.length;d++)1<a[d].colSpan&&(e+=a[d].colSpan-1);document.getElementById("layout_column").value=e;layout_creater_options();a=Array(b).fill(0).map(function(a){return Array(e).fill(0)});for(d=0;d<b;d++)for(var n=c[d].cells,g=0,q=0,h=n.length;q<h;q++){for(var f=n[q];a[d][g];)g++;var k=0;if(1<f.colSpan){var l=g+f.colSpan;k=1}else l=
g+1;var m=0;if(1<f.rowSpan){var p=d+f.rowSpan;m=1}else p=d+1;for(var r=d,u=1;r<p;r++)for(var t=g,v=1;t<l;t++)k&&0===v?a[r][t]="colspan":m&&0===u?a[r][t]="rowspan":(k&&1===v&&(v=0),m&&1===u&&(u=0),a[r][t]=f.id?f.id:"feed");g=l}c=1;for(d=0;d<b;d++)for(n=0;n<e;n++)g=document.getElementById("ls_"+c),"rowspan"===a[d][n]?g.value="rowspan":"colspan"===a[d][n]?g.value="colspan":"feed"===a[d][n]?(g.value="feed",feed_count++):"bookmarks"===a[d][n]?g.value="bookmarks":"notes"===a[d][n]?g.value="notes":"weather"===
a[d][n]&&(g.value="weather"),c++;layout_creater_update()}
function layout_creater_update(){for(var c={},b=0;2>b;c={$jscomp$loop$prop$column_count$26:c.$jscomp$loop$prop$column_count$26},b++){var a=Number(document.getElementById("layout_row").value);c.$jscomp$loop$prop$column_count$26=Number(document.getElementById("layout_column").value);for(var e=Array(a).fill(0).map(function(a){return function(b){return Array(a.$jscomp$loop$prop$column_count$26).fill(0)}}(c)),d=Array(a).fill(0).map(function(a){return function(b){return Array(a.$jscomp$loop$prop$column_count$26).fill(0)}}(c)),n=
0,g=0,q=0,h=1,f=0;f<a;f++)for(var k=0,l="";k<c.$jscomp$loop$prop$column_count$26;k++){var m=document.getElementById("ls_"+h);m.disabled=!1;var p=m.value;"bookmarks"===p?n=h:"notes"===p?q=h:"weather"===p?g=h:"rowspan"===p?e[f][k]=1:"colspan"===p&&(d[f][k]=1);l='<option value="feed">Feed</option>';l+='<option value="bookmarks">Bookmarks</option>';l+='<option value="notes">Notes</option>';l+='<option value="weather">Weather</option>';0<f&&(l+='<option value="rowspan">\u2193 Rowspan</option>');0<k&&(l+=
'<option value="colspan">\u2192 Colspan</option>');m.innerHTML=l;m.value=p;h++}h=1;for(f=0;f<a;f++)for(k=0;k<c.$jscomp$loop$prop$column_count$26;k++){l=document.getElementById("ls_"+h).value;if("rowspan"===l&&(d[f-1][k]||d[f-1][k+1])){for(m=1;k+m<c.$jscomp$loop$prop$column_count$26&&d[f-1][k+m];)document.getElementById("ls_"+(h+m)).value="rowspan",m++;for(m=1;0<=k-m&&d[f-1][k-m+1];)document.getElementById("ls_"+(h-m)).value="rowspan",m++}if("rowspan"===l&&1<f&&e[f-1][k])for(m=1;0<=f-m;){if(d[f-m][k]||
d[f-m][k+1]){for(var r=0;d[f-m][k-r];)r++;for(p=0;d[f-m][k+p];)p++;for(r=-r;r<p;r++)document.getElementById("ls_"+(h+r)).value="rowspan"}if("rowspan"!==document.getElementById("ls_"+(h-c.$jscomp$loop$prop$column_count$26*m)).value)break;m++}if("colspan"===l&&(e[f][k-1]||f+1<a&&e[f+1][k-1])){for(l=0;0<f-l&&e[f-l][k-1];)document.getElementById("ls_"+(h-c.$jscomp$loop$prop$column_count$26*l)).value="rowspan",l++;document.getElementById("ls_"+(h-c.$jscomp$loop$prop$column_count$26*l)).value="colspan";
for(l=1;f+l<a&&e[f+l][k-1];)document.getElementById("ls_"+(h+c.$jscomp$loop$prop$column_count$26*l)).value="rowspan",l++}h++}h=1;for(f=0;f<a;f++)for(k=0,l="";k<c.$jscomp$loop$prop$column_count$26;k++){m=document.getElementById("ls_"+h);p=m.value;l='<option value="feed">Feed</option>';n&&n!==h||(l+='<option value="bookmarks">Bookmarks</option>');q&&q!==h||(l+='<option value="notes">Notes</option>');g&&g!==h||(l+='<option value="weather">Weather</option>');if(0<f&&(l+='<option value="rowspan">\u2193 Rowspan</option>',
"rowspan"===p))for(f<a-1&&e[f+1][k]&&(m.disabled=!0),r=1;0<=f-r;){d[f-r][k]&&(m.disabled=!0,document.getElementById("ls_"+(h-1)).disabled=!0);if("rowspan"!==document.getElementById("ls_"+(h-c.$jscomp$loop$prop$column_count$26*r)).value)break;r++}0<k&&(l+='<option value="colspan">\u2192 Colspan</option>',"colspan"===p&&k<c.$jscomp$loop$prop$column_count$26-1&&d[f][k+1]&&(m.disabled=!0));m.innerHTML=l;m.value=p;h++}}layout_update_preview(1)}
function layout_update_preview(c){for(var b=Number(document.getElementById("layout_row").value),a=Number(document.getElementById("layout_column").value),e=!1,d=!1,n=!1,g,q=0,h="<tbody>",f=1,k=0;k<b;k++){h+="<tr>";for(var l=0;l<a;l++){g=document.getElementById("ls_"+f);if("rowspan"!==g.value&&"colspan"!==g.value){"bookmarks"===g.value&&!1===e?(h+='<td id="bookmarks"',e=!0,g="B"):"notes"===g.value&&!1===n?(h+='<td id="notes"',n=!0,g="N"):"weather"===g.value&&!1===d?(h+='<td id="weather"',d=!0,g="W"):
(h+='<td class="feed_box"',q++,g=q);for(var m=1,p=f+a;document.getElementById("ls_"+p)&&"rowspan"===document.getElementById("ls_"+p).value;)m++,p+=a;p=1;for(var r=f+1;document.getElementById("ls_"+r)&&"colspan"===document.getElementById("ls_"+r).value;)p++,r++;1<m&&(h+=' rowspan="'+m+'"');1<p&&(h+=' colspan="'+p+'"');h+=">";c&&(h+=g);h+="</td>"}f++}h+="</tr>"}h+="</tbody>";document.getElementById("layout_preview").innerHTML=h;document.getElementById("feed_count").innerHTML=q}
function layout_save(c){layout_update_preview(0);var b=document.getElementById("feed_count").innerHTML,a=document.getElementById("layout_preview"),e=a.children[0].innerHTML,d=0,n=0,g=0;null!=a.querySelector("#bookmarks")&&(d=1);null!=a.querySelector("#notes")&&(n=1);null!=a.querySelector("#weather")&&(g=1);console.log("b:"+d+" n:"+n+" w:"+g);var q=xhr("POST","php/settings_worker.php");q.setRequestHeader("Content-Type","application/x-www-form-urlencoded; charset=UTF-8");q.onreadystatechange=function(){4==
q.readyState&&200==q.status&&(0===c?window.location.replace("/settings.php?tab=layout?saved"):window.location.replace("/"))};q.send("feed_count="+b+"&table="+encodeURIComponent(e)+"&b="+d+"&n="+n+"&w="+g)}function theme_preview(){var c=document.getElementById("theme_select").value;document.getElementById("theme_prev").innerHTML='<img src="css/_prev/'+c+'.png" alt="preview">'}
document.addEventListener("DOMContentLoaded",function(){show_tab("feeds");document.getElementById("layout").addEventListener("click",function(){show_tab("layout")},!1);document.getElementById("theme").addEventListener("click",function(){show_tab("theme")},!1);document.getElementById("user").addEventListener("click",function(){show_tab("user")},!1);document.getElementById("feeds").addEventListener("click",function(){show_tab("feeds")},!1);document.getElementById("bookmarks").addEventListener("click",
function(){show_tab("bookmarks")},!1);document.getElementById("weather").addEventListener("click",function(){show_tab("weather")},!1);parse_url(location.search.substr(1));document.getElementById("feed_edit_select").addEventListener("click",function(){feed_edit()},!1);document.getElementById("btn_cat_add").addEventListener("click",function(){cat_add()},!1);document.getElementById("b_cats").addEventListener("click",function(){cat_load()},!1);document.getElementById("weather_update").addEventListener("click",
function(){weather_update()},!1);document.getElementById("weather_icon").addEventListener("click",function(){weather_icon()},!1);weather_icon();layout_creater_init();document.getElementById("layout_row").addEventListener("click",function(){layout_creater_options();layout_creater_update()},!1);document.getElementById("layout_column").addEventListener("click",function(){layout_creater_options();layout_creater_update()},!1);document.getElementById("theme_select").addEventListener("click",function(){theme_preview()},
!1);theme_preview();document.getElementById("layout_save").addEventListener("click",function(){layout_save(0)},!1);document.getElementById("submit_save").addEventListener("click",function(){layout_save(1)},!1)});